import { $env, $flag } from "@oh-my-pi/pi-utils";

const SIXEL_START_REGEX = /\x1bP(?:[0-9;]*)q/u;
const SIXEL_END_SEQUENCE = "\x1b\\";
const SIXEL_END_BELL = "\x07";
const SIXEL_SEQUENCE_REGEX = /\x1bP(?:[0-9;]*)q[\s\S]*?(?:\x1b\\|\x07)/gu;
const SIXEL_PLACEHOLDER_PREFIX = "__OMP_SIXEL_SEQUENCE_";

/**
 * Returns whether SIXEL passthrough is explicitly enabled.
 *
 * Both gates must be enabled to preserve SIXEL control sequences:
 * - PI_FORCE_IMAGE_PROTOCOL=sixel
 * - PI_ALLOW_SIXEL_PASSTHROUGH=1
 */
export function isSixelPassthroughEnabled(): boolean {
	const forcedProtocol = $env.PI_FORCE_IMAGE_PROTOCOL?.trim().toLowerCase();
	return forcedProtocol === "sixel" && $flag("PI_ALLOW_SIXEL_PASSTHROUGH");
}
/** Returns true when the text contains a SIXEL start sequence. */
export function containsSixelSequence(text: string): boolean {
	return SIXEL_START_REGEX.test(text);
}

/**
 * Returns a boolean mask indicating which lines belong to a SIXEL sequence block.
 * Supports multi-line SIXEL payloads generated by libsixel. `startsInside`
 * marks rows that continue a payload whose start row was dropped upstream
 * (a producer's bounded retention), so the leading continuation rows are
 * still classified as SIXEL.
 */
export function getSixelLineMask(lines: readonly string[], startsInside = false): boolean[] {
	let inSequence = startsInside;
	return lines.map(line => {
		const hasStart = containsSixelSequence(line);
		if (hasStart) {
			inSequence = true;
		}
		const isSixelLine = inSequence;
		if (inSequence && (line.includes(SIXEL_END_SEQUENCE) || line.includes(SIXEL_END_BELL))) {
			inSequence = false;
		}
		return isSixelLine;
	});
}

/**
 * Whether a SIXEL payload is still open after `lines`: the span state the
 * next row enters with. `startsInside` is the state `lines[0]` enters with.
 */
export function sixelSpanContinues(lines: readonly string[], startsInside = false): boolean {
	let inSequence = startsInside;
	for (const line of lines) {
		if (containsSixelSequence(line)) inSequence = true;
		if (inSequence && (line.includes(SIXEL_END_SEQUENCE) || line.includes(SIXEL_END_BELL))) inSequence = false;
	}
	return inSequence;
}

/** Earliest SIXEL terminator (`ST` or `BEL`) in `text`, if any. */
function findSixelTerminator(text: string): { index: number; length: number } | undefined {
	const st = text.indexOf(SIXEL_END_SEQUENCE);
	const bel = text.indexOf(SIXEL_END_BELL);
	if (st < 0 && bel < 0) return undefined;
	if (bel < 0 || (st >= 0 && st < bel)) return { index: st, length: SIXEL_END_SEQUENCE.length };
	return { index: bel, length: SIXEL_END_BELL.length };
}

/**
 * Replace every SIXEL sequence in `lines` with `replacement`, keeping all
 * other text. Only the payload bytes go: output before a start marker or
 * after a terminator on the same row survives, each sequence gets its own
 * replacement (two payloads on consecutive rows are two replacements), and
 * the continuation rows of a multi-row payload become empty. `startsInside`
 * marks rows that continue a payload whose start row was dropped upstream;
 * the first such row carries the replacement.
 */
export function replaceSixelSequences(lines: readonly string[], replacement: string, startsInside = false): string[] {
	let inside = startsInside;
	let replaced = !startsInside;
	return lines.map(line => {
		let out = "";
		let rest = line;
		// A continued payload owes its label to the first retained row even when
		// that row is blank (the retention cut can land on an empty payload row).
		if (inside && !replaced) {
			out += replacement;
			replaced = true;
		}
		while (rest.length > 0) {
			if (inside) {
				const end = findSixelTerminator(rest);
				if (end === undefined) break;
				rest = rest.slice(end.index + end.length);
				inside = false;
				continue;
			}
			const start = SIXEL_START_REGEX.exec(rest);
			if (!start) {
				out += rest;
				break;
			}
			out += rest.slice(0, start.index) + replacement;
			rest = rest.slice(start.index + start[0].length);
			inside = true;
			replaced = true;
		}
		return out;
	});
}

/** Returns true when the line contains a SIXEL start sequence. */
export function isSixelLine(line: string): boolean {
	return containsSixelSequence(line);
}

/**
 * Sanitizes text while preserving embedded SIXEL sequences when passthrough is enabled.
 */
export function sanitizeWithOptionalSixelPassthrough(text: string, sanitize: (text: string) => string): string {
	if (!isSixelPassthroughEnabled() || !containsSixelSequence(text)) {
		return sanitize(text);
	}

	const preservedSequences: string[] = [];
	const tokenized = text.replace(SIXEL_SEQUENCE_REGEX, match => {
		const token = `${SIXEL_PLACEHOLDER_PREFIX}${preservedSequences.length}__`;
		preservedSequences.push(match);
		return token;
	});

	const sanitized = sanitize(tokenized);
	return sanitized.replace(/__OMP_SIXEL_SEQUENCE_(\d+)__/gu, (_, indexText: string) => {
		const index = Number.parseInt(indexText, 10);
		return preservedSequences[index] ?? "";
	});
}
